// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate_swagger = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "email": "gabriel777sh@gmail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/cek_http": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "test"
                ],
                "summary": "Cek kondisi HTTP client pool",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token Login",
                        "name": "X-TOKEN",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        },
                        "headers": {
                            "X-TOKEN": {
                                "type": "string",
                                "description": "Token login"
                            }
                        }
                    },
                    "206": {
                        "description": "Error lain",
                        "schema": {
                            "$ref": "#/definitions/model.FailResponse"
                        }
                    },
                    "207": {
                        "description": "Gagal Login",
                        "schema": {
                            "$ref": "#/definitions/model.FailResponse"
                        }
                    },
                    "209": {
                        "description": "Invalid JSON input",
                        "schema": {
                            "$ref": "#/definitions/model.FailResponse"
                        }
                    },
                    "210": {
                        "description": "Error Middleware Internal",
                        "schema": {
                            "$ref": "#/definitions/model.FailResponse"
                        }
                    },
                    "214": {
                        "description": "Data Pengguna Tidak Ditemukan",
                        "schema": {
                            "$ref": "#/definitions/model.FailResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/cek_middleware": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "test"
                ],
                "summary": "Cek kondisi middleware yang digunakan untuk authorization",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token Login",
                        "name": "X-TOKEN",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful Operation",
                        "schema": {
                            "$ref": "#/definitions/model.UserData"
                        },
                        "headers": {
                            "X-TOKEN": {
                                "type": "string",
                                "description": "Token login"
                            }
                        }
                    },
                    "206": {
                        "description": "Error lain",
                        "schema": {
                            "$ref": "#/definitions/model.FailResponse"
                        }
                    },
                    "207": {
                        "description": "Gagal Login",
                        "schema": {
                            "$ref": "#/definitions/model.FailResponse"
                        }
                    },
                    "209": {
                        "description": "Invalid JSON input",
                        "schema": {
                            "$ref": "#/definitions/model.FailResponse"
                        }
                    },
                    "210": {
                        "description": "Error Middleware Internal",
                        "schema": {
                            "$ref": "#/definitions/model.FailResponse"
                        }
                    },
                    "214": {
                        "description": "Data Pengguna Tidak Ditemukan",
                        "schema": {
                            "$ref": "#/definitions/model.FailResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "Login user dengan informasi dari JSON input.\nJika sukses, pada response header akan disertakan token login (key: X-TOKEN)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "login"
                ],
                "summary": "Login user",
                "parameters": [
                    {
                        "description": "Body JSON input",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UserData"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successful Operation",
                        "schema": {
                            "$ref": "#/definitions/model.LoginResponse"
                        },
                        "headers": {
                            "X-TOKEN": {
                                "type": "string",
                                "description": "Token login"
                            }
                        }
                    },
                    "206": {
                        "description": "Error lain",
                        "schema": {
                            "$ref": "#/definitions/model.FailResponse"
                        }
                    },
                    "207": {
                        "description": "Gagal Login",
                        "schema": {
                            "$ref": "#/definitions/model.FailResponse"
                        }
                    },
                    "209": {
                        "description": "Invalid JSON input",
                        "schema": {
                            "$ref": "#/definitions/model.FailResponse"
                        }
                    },
                    "210": {
                        "description": "Error Middleware Internal",
                        "schema": {
                            "$ref": "#/definitions/model.FailResponse"
                        }
                    },
                    "214": {
                        "description": "Data Pengguna Tidak Ditemukan",
                        "schema": {
                            "$ref": "#/definitions/model.FailResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.FailResponse": {
            "type": "object",
            "required": [
                "msg"
            ],
            "properties": {
                "msg": {
                    "type": "string",
                    "example": "Pesan kesalahan"
                }
            }
        },
        "model.LoginResponse": {
            "type": "object",
            "properties": {
                "nama": {
                    "type": "string",
                    "example": "John Doe"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "model.UserData": {
            "type": "object",
            "required": [
                "nama"
            ],
            "properties": {
                "nama": {
                    "type": "string",
                    "example": "John Doe"
                }
            }
        }
    },
    "tags": [
        {
            "description": "API yang digunakan untuk login",
            "name": "login"
        },
        {
            "description": "API yang digunakan untuk coba-coba",
            "name": "test"
        }
    ]
}`

// SwaggerInfo_swagger holds exported Swagger Info so clients can modify it
var SwaggerInfo_swagger = &swag.Spec{
	Version:          "0.0.1",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{"http", "https"},
	Title:            "Coba Gin Golang",
	Description:      "Percobaan Swagger & Gin pada Golang untuk pembuatan API\n\n<h4>Note: HTTP status dari response API secara umum:</h4>\n- <strong>200</strong> : Sukses\n- <strong>206</strong> : Error lain\n- <strong>209</strong> : Data input salah / tidak valid\n- <strong>210</strong> : Error middleware internal\n- <strong>214</strong> : Data tidak ditemukan\n- <strong>401</strong> : Token invalid\n- <strong>500</strong> : Internal server error (fatal)\n\nJika response code tidak <strong>200</strong>, maka yang dikembalikan adalah JSON dengan 1 elemen \"msg\"",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate_swagger,
}

func init() {
	swag.Register(SwaggerInfo_swagger.InstanceName(), SwaggerInfo_swagger)
}
